### ISSUE TITLE
viewing the output

### ISSUE THREAD

**Issue by nikky4D** [lmb-freiburg/flownet2-docker#1]
Hi,

I have compiled and run a test sample. However, the output is in .flo format. Can you tell me how I can view the output, exporting it as a .png or other data file?

**Comment by nikolausmayer** [comment]
Hi nikky4D,

check this out (disclaimer: not our code): http://vision.middlebury.edu/flow/code/flow-code/
This compiles into a small executable which can convert .flo files into viewable images.

**Comment by nikky4D** [comment]
Great. Thank you.

**Comment by sakherg** [comment]
Hi,
For python, there is this package that can do the job: [https://github.com/georgegach/flowiz](https://github.com/georgegach/flowiz)
