### ISSUE TITLE
How long should a frame take to process?

### ISSUE THREAD

**Issue by positlabs** [lmb-freiburg/flownet2-docker#10]
On a 1280x720 image, it's taking about 8 seconds using a K80.

I'm not seeing much activity on my GPU, and the CPU is pinned at 100%, so I'm inclined to think the work is not being done on the GPU. 

I am using a modified dockerfile, so maybe I screwed something up there. I just downgraded in order to use an older version of cuda. https://github.com/positlabs/fast-artistic-videos-docker/blob/master/flownet2-docker/Dockerfile

Seems like the drivers / nvidia-docker are working, at least with the style transfer stuff.

**Comment by nikolausmayer** [comment]
8 seconds really does seem too long (unless you are counting the network setup time). I've run FlowNet2 (although not in Docker) on a GTX 980M and got around 1 fps even on 1920x1080 images. But I don't think just downgrading to CUDA 7.5 should have this much impact.

Is there anything in the output (if you run the script with `-vv` for verbosity) which could indicate that the GPU is not correctly used? Or not the right GPU?

There is an issue with FlowNet2 where the network "randomly" produces NaN pixels (I don't think it's random but we never found the exact cause), and the Docker runscript accounts for that by redoing the forward pass up to 5 times (see https://github.com/lmb-freiburg/flownet2-docker/blob/master/FN2_run-flownet-docker.py#L124). This loop could be safely removed if the check is not important for you.

**Comment by positlabs** [comment]
It says that it's using cudnn in the logs. I don't see any else that sticks out.

I'm building off of the flownet2-docker container, but referencing the scripts directly.

Another user is having the same issue, using the docker image via the run command. https://github.com/manuelruder/fast-artistic-videos/issues/10#issuecomment-445358488

**Comment by nikolausmayer** [comment]
The Python runscript is definitely not a _fast_ way to run the network: it loads and feeds images sequentially and uses Python for I/O which is not necessarily the best option.
Note the line 
`net = caffe.Net(tmp.name, args.caffemodel, caffe.TEST)` in user "oleprinds"' script: the network is reinitialized from scratch for every input. If all your image data has the same dimensions (which is likely if you are processing a video), this is unnecessary. Resetting the net all the time uses a ton of CPU time while the GPU idles.

Our scripts don't really care much about efficiency: the Docker images are primarily intended for users who just want to run FlowNets as easily as possible.

**Comment by positlabs** [comment]
Ah! Thanks for the insight! I modified the [run-flownet-many.py](https://github.com/lmb-freiburg/flownet2/blob/master/scripts/run-flownet-many.py) script so it doesn't re-init the network for every frame. Works great! Probably a 10x speed improvement.

https://github.com/positlabs/fast-artistic-videos-docker/blob/master/run-flownet-many.py

**Comment by Tsugikuni-Yoriichi** [comment]
I use top command and nvidia-smi to watch the usage of resources. I fond python reaches 100% however the mem cost in GPU 3060Ti only cost 136MB. It is quite slow this time. I have tried this work in some other machines and it get really fast than this machine. I am quite bothered with this.
