### ISSUE TITLE
Will this work on latest version of CUDA 10? I am new please suggest me the changes in case it won’t I am getting error docker:error response from daemon:oci runtime create failed when i the 2.1 

### ISSUE THREAD

**Issue by vivekdahiya95** [lmb-freiburg/flownet2-docker#13]

**Comment by nikolausmayer** [comment]
Hi, if I remember correctly, you need only minor changes for CUDA 10. Some header includes may have changed, and perhaps a function is now in a different namespace. These should be easily found in the compiler errors.
The compiler will probably also complain (a lot!) that some `switch` statements to not cover newly added values in CUDA 10, so this might spam the compile output. It's just warnings though, no need to fix it.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
