### ISSUE TITLE
convert .flo file to .npy file 

### ISSUE THREAD

**Issue by YoungJ-Baek** [lmb-freiburg/flownet2-docker#17]
I want to get vector map of optical flow
So I try to convert `.flo `file into vector map file such as `.npy` file.
However I can only find the way how to convert it into `.png` file or something for image file.
Can you help me with this matter?

Also I want to try many layers and make custom network
but I'm not familiar with Docker and Ubuntu, so I don't know how to access and modify source codes
I can trace back the source codes to get vector map of optical flow if there's no way to convert `.flo` to `.npy` or something else.

**Comment by tonmoy-saikia** [comment]
Here is a snippet on reading .flo files with python. 
https://github.com/lmb-freiburg/netdef_slim/blob/master/utils/io.py#L145

**Comment by YoungJ-Baek** [comment]
Thank you for helping me!
Now I can read vector map and am surprised for the large number of data so that I can't read by set_printoptions(threshold=np.nan)
So I am trying to find the best way to get best feature of vector map.
However your advice help me a lot and it is my new task to struggle!
Thanks again!
