### ISSUE TITLE
.flo file data

### ISSUE THREAD

**Issue by YoungJ-Baek** [lmb-freiburg/flownet2-docker#18]
Now I'm using data from `.flo` file.
However I want to know exact magnitude of vector
So does `.flo` file provide vector by pixel size?
(ex/ (2, 5) means 2 pixel for x axis and 5 pixel for y axis)

**Comment by nikolausmayer** [comment]
Yes.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
