### ISSUE TITLE
about image quality

### ISSUE THREAD

**Issue by juanfe0705** [lmb-freiburg/flownet2-docker#22]
Everything works fine for me, I can generate .flo without trouble and I can convert them to .png
However, when I see the .png image it looks very pixelated as in Figure 1 (left) of this paper:

-  https://lmb.informatik.uni-freiburg.de/Publications/2017/IMSKDB17/paper-FlowNet_2_0__CVPR.pdf 

but I would like to have the image as in figure 1 (right)

can you help me?

**Comment by nikolausmayer** [comment]
Try another model. The different pretrained models in this repository perform differently depending on whether your input has small or large motions, homogeneous regions, or black backgrounds.
If you tested a Sintel sample, I would wager a guess that you did not run the full FlowNet2.0 model.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
