### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by Ahleroy** [lmb-freiburg/flownet2-docker#23]
I do not have any output when using run-network.sh.
The printed output is : 
```
Using GPU:       1
Running network: FlowNet2
Working dir:     /flownet2/flownet2/scripts
First input:     ./data/0000000-imgL.png
Second input:    ./data/0000001-imgL.png
Output:          ./flow.flo
```
But I have no file created.
I do not know what  "flownet/flownet/scripts" folder the script refers to.
Is there anything I am doing wrong ?

**Comment by nikolausmayer** [comment]
Please post the complete command line with which you ran the example. You can also run the command with `-vv` to get a more verbose output which might help you identify problems.

**Comment by Ahleroy** [comment]
The basic command doesn't work : 

`./run-network.sh -n FlowNet2 -v data/0000000-imgL.png data/0000001-imgL.png flow.flo`

Using -vv generates the same output. Adding '-g 1' doesn't change either.

**Comment by nikolausmayer** [comment]
Ok, so with `-vv` there should be a lot of output. Does everything look ok there?
One "common" issue I found is that depending on your filesystem setup, the Docker container may have to be on the same drive as the location of the data and where the script is called.

**Comment by Ahleroy** [comment]
Look like the line "dummy=`which nvidia-docker`;" was making everything stop.
When commented the script continues and says :
`./run-network.sh: 172: UID: parameter not set`

**Comment by nikolausmayer** [comment]
That's interesting. What OS are you running? The `dummy` line should not fail (or rather, it is ok if the enclosed command fails). I am not aware of a system in which `$UID` does not exist, but you could just replace it with whatever command produces your user's numeric ID.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
