### ISSUE TITLE
Installation problem such as RPC failed and  gnutls_handshake() failed

### ISSUE THREAD

**Issue by Tsugikuni-Yoriichi** [lmb-freiburg/flownet2-docker#25]
while I have prepared all the requirements for make in the flownet-docker directory, in the step 14, it failed with different reasons:
(1) 
Step 14/18 : RUN git clone https://github.com/lmb-freiburg/flownet2                      &&     cp ./FN2_Makefile.config ./flownet2/Makefile.config                     &&     cp ./FN2_run-flownet-docker.py ./flownet2/scripts/run-flownet-docker.py &&     cd flownet2                                                             &&     rm -rf .git                                                             &&     cd models                                                               &&     bash download-models.sh                                                 &&     rm flownet2-models.tar.gz                                               &&     cd ..                                                                   &&     make -j`nproc`                                                          &&     make -j`nproc` pycaffe
 ---> Running in e21fff5da1e7
Cloning into 'flownet2'...
**fatal: unable to access 'https://github.com/lmb-freiburg/flownet2/': gnutls_handshake() failed: The TLS connection was non-properly terminated.**
The command '/bin/sh -c git clone https://github.com/lmb-freiburg/flownet2                      &&     cp ./FN2_Makefile.config ./flownet2/Makefile.config                     &&     cp ./FN2_run-flownet-docker.py ./flownet2/scripts/run-flownet-docker.py &&     cd flownet2                                                             &&     rm -rf .git                                                             &&     cd models                                                               &&     bash download-models.sh                                                 &&     rm flownet2-models.tar.gz                                               &&     cd ..                                                                   &&     make -j`nproc`                                                          &&     make -j`nproc` pycaffe' returned a non-zero code: 128
Makefile:8: recipe for target 'flownet2' failed
make: *** [flownet2] Error 128

(2)
Step 14/18 : RUN git clone https://github.com/lmb-freiburg/flownet2                      &&     cp ./FN2_Makefile.config ./flownet2/Makefile.config                     &&     cp ./FN2_run-flownet-docker.py ./flownet2/scripts/run-flownet-docker.py &&     cd flownet2                                                             &&     rm -rf .git                                                             &&     cd models                                                               &&     bash download-models.sh                                                 &&     rm flownet2-models.tar.gz                                               &&     cd ..                                                                   &&     make -j`nproc`                                                          &&     make -j`nproc` pycaffe
 ---> Running in ef5027eaa99b
Cloning into 'flownet2'...
**error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.**
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
The command '/bin/sh -c git clone https://github.com/lmb-freiburg/flownet2                      &&     cp ./FN2_Makefile.config ./flownet2/Makefile.config                     &&     cp ./FN2_run-flownet-docker.py ./flownet2/scripts/run-flownet-docker.py &&     cd flownet2                                                             &&     rm -rf .git                                                             &&     cd models                                                               &&     bash download-models.sh                                                 &&     rm flownet2-models.tar.gz                                               &&     cd ..                                                                   &&     make -j`nproc`                                                          &&     make -j`nproc` pycaffe' returned a non-zero code: 128
Makefile:8: recipe for target 'flownet2' failed
make: *** [flownet2] Error 128

Actually I have made it several times, and it can successfully make the final result with about 8 Gb in the docker images. But this time, it stopped in the 14 step and there is only 2.76 Gb in the docker images. I have tried my git, it is fast with a proxy setting. Is there any suggestions?

**Comment by WANGYuSCU** [comment]
I solved it by myself. Sometimes, the git in the docker does not work because it can not get access to the system proxy.
I just use some mirror for downloading the flownet by put  changing:
git clone https://github.com/imb-freiburg/flownet2 to git clone https://github.com.cnpmjs.org/imb-freiburg/flownet2.

**Comment by Tsugikuni-Yoriichi** [comment]
I solved it by myself. Sometimes, the git in the docker does not work because it can not get access to the system proxy.
I just use some mirror for downloading the flownet by put changing:
git clone https://github.com/imb-freiburg/flownet2 to git clone https://github.com.cnpmjs.org/imb-freiburg/flownet2.
