### ISSUE TITLE
CUDA 8 on GTX 690 doesn't work -> could I use with CUDA 7.5 ?

### ISSUE THREAD

**Issue by Setzar** [lmb-freiburg/flownet2-docker#5]
I am trying to put docker-nvidia on Debian 9 with GTX 690 and there is a problem with the installation of the driver with CUDA kernel. I would like to know if I can use FlowNet2 with CUDA 7.5 ? 

Thank you.

**Comment by nikolausmayer** [comment]
Hi Setzar,
the codebase should run fine; I don't think we use any new features. If there are fitting base images for CUDA 7.5, I don't see a major problem.
