### ISSUE TITLE
Hash Sum mismatch: shared-mime-info

### ISSUE THREAD

**Issue by vvaquero** [lmb-freiburg/flownet2-docker#6]
Just in case when running "make" someone is getting the error (Hash Sum mismatch) referent to the package shared-mime-info. 

I solved it by modifying the flownet2-docker/Dockerfile. 
In Line 20, under command "RUN apt-get update && \ " add the instruction to specifically install this package " apt-get install shared-mime-info -y --no-install-recommends && \ "

That worked for me.

**Comment by nikolausmayer** [comment]
Huh, thanks for working this out. I haven't seen it myself, but it seems to happen to many people.

When I get around to setting up a repo wiki, this will go in there. In looks like the issue could happen to any package, not just `shared-mime-info`, so I'm reluctant to update the Dockerfile (and I don't want individual install steps for every package).
