### ISSUE TITLE
How to open .flow file?

### ISSUE THREAD

**Issue by deepkshikha** [lmb-freiburg/flownet2-docker#8]

**Comment by nikolausmayer** [comment]
For `.flo` files, check http://vision.middlebury.edu/flow/data/ (search page for "code").

For `.pfm` files, use [our Python code](https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlow/assets/code/python_pfm.py), [CImg](http://cimg.eu/) for C++, or ask Google for Matlab code.

**Comment by deepkshikha** [comment]
@nikolausmayer  Thanks for response. I am able to convert Thanks
