### ISSUE TITLE
How can I generate 2-channel optical flow image and save its x, y channel as .jpg image?

### ISSUE THREAD

**Issue by fairyzhxz** [lmb-freiburg/flownet2-docker#9]
After using flownet2.0 method, I have generated *.flo files. But I don't know how to convert * .flo files to 2-channel optical flow image and save its x, y channel as .jpg image. Can you help me? Thanks so much.

**Comment by nikolausmayer** [comment]
Please see https://github.com/lmb-freiburg/flownet2-docker/issues/1
